# Generated by Django 3.0.3 on 2020-03-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200328_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='team',
        ),
    ]
