# Generated by Django 3.0.3 on 2020-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelist',
            name='myname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
