# Generated by Django 3.0.3 on 2020-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_votelist_votenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votelist',
            old_name='name',
            new_name='lastteam',
        ),
        migrations.AddField(
            model_name='votelist',
            name='team',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
